# Setup
title: 'D-Pop 2020 forel√∏big webside'
url: https://d-dpop.github.io

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
# safe: true # breaks local rendering if enabled
timezone: Denmark/Copenhagen


# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
